[tool.poetry]
name = "yandexdevops"
version = "0.1.0"
description = ""
authors = ["NazKar@Nazir <karimov.nazir00@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flake8 = "^7.3.0"
isort = "^7.0.0"
black = "^25.12.0"
alpine = "^1.0.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
